/* 
DROP TABLE CHITIETHOADON;
DROP TABLE CHITIETKHO;
DROP TABLE HOADON;
DROP TABLE KHACHHANG;
DROP TABLE KHOVAN;
DROP TABLE NHANVIEN;
DROP TABLE SANPHAM;
*/

CREATE TABLE SANPHAM (
    MaSP VARCHAR(30) PRIMARY KEY,
    TenSP VARCHAR(100),
    GiaSP INT,
    SoLuong INT,
    PhanLoai VARCHAR(50),
    NSX DATE,
    HSD DATE,
    MoTa VARCHAR(500),
    TTCT VARCHAR(2000)
);

CREATE TABLE NHANVIEN (
    MaNV VARCHAR(10) PRIMARY KEY,
    TenNV VARCHAR(50),
    SDTNV VARCHAR(20),
    NgaySinh DATE,
    CCCD VARCHAR(20),
    DiaChi VARCHAR(200),
    ChucVu VARCHAR(50),
    Luong INT
);

CREATE TABLE KHACHHANG (
    SDTKH VARCHAR(20) PRIMARY KEY,
    TenKH VARCHAR(50)
);

CREATE TABLE HOADON (
    MaHD VARCHAR(10) PRIMARY KEY,
    NgayMua DATE,
    MaNV VARCHAR(10),
    SDTKH VARCHAR(20),
    HinhThuc VARCHAR(50),
    CONSTRAINT fk_NV_HD FOREIGN KEY (MaNV) REFERENCES NHANVIEN (MaNV),
    CONSTRAINT fk_KH_HD FOREIGN KEY (SDTKH) REFERENCES KHACHHANG (SDTKH)
);

CREATE TABLE KHOVAN (
    MaLoHang VARCHAR(10) PRIMARY KEY,
    NgayNhap DATE,
    NgayXuat DATE,
    TenCH VARCHAR(100)
);

CREATE TABLE CHITIETKHO (
    MaLoHang VARCHAR(10),
    MaSP VARCHAR(30),
    SoLuong INT,
    PRIMARY KEY (MaLoHang, MaSP),
    CONSTRAINT fk_LH_CTK FOREIGN KEY (MaLoHang) REFERENCES KHOVAN (MaLoHang),
    CONSTRAINT fk_SP_CTK FOREIGN KEY (MaSP) REFERENCES SANPHAM (MaSP)
);

CREATE TABLE CHITIETHOADON (
    MaHD VARCHAR(10),
    MaSP VARCHAR(30),
    SoLuong INT,
    Gia INT,
    PRIMARY KEY (MaHD, MaSP),
    CONSTRAINT fk_HD_CTHD FOREIGN KEY (MaHD) REFERENCES HOADON (MaHD),
    CONSTRAINT fk_SP_CTHD FOREIGN KEY (MaSP) REFERENCES SANPHAM (MaSP)
);

ALTER TABLE SANPHAM ADD  GIAGIAM INT;

CREATE TABLE NGUOIDUNG (
    MaNV VARCHAR(10) PRIMARY KEY,
    username VARCHAR(20) not null,
    password varchar(50) not null
)

ALTER TABLE KHOVAN DROP COLUMN NGAYXUAT;
